# Generated by Django 5.2.7 on 2025-11-02 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите категорию продукта",
                max_length=50,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Введите категорию продукта",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic",
            field=models.ImageField(
                blank=True,
                help_text="Вставьте фото собаки",
                null=True,
                upload_to="Product/pics.png",
                verbose_name="Фото продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                blank=True,
                help_text="Введите цену продукта",
                null=True,
                verbose_name="Цена продукта",
            ),
        ),
    ]
