# Generated by Django 4.2.2 on 2025-12-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_name_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status_published",
            field=models.BooleanField(default=False),
        ),
    ]
