# Generated by Django 4.2.2 on 2025-12-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_status_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status_published",
            field=models.BooleanField(choices=[("True", "False")], default=False),
        ),
    ]
